###

GET http://localhost:8000/test

###

POST http://localhost:8000/api/register
Content-Type: application/json

{
    "name": "test",
    "email": "test4@test.com",
    "password": "12345678"
}

###

POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "test3@test.com",
    "password": "12345678"
}

###

@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImVtYWlsIjoidGVzdDNAdGVzdC5jb20iLCJleHAiOjE2NTI3NjAzODI2NTMsImlzcyI6InN1cnZleS1hcHAifQ.Xv8aAPPgsA0HU7oOjUCoKY-GID_ZNYQPoOcxg2FDKBv890M_p0yT95gbr-wG7hBEE42va7H2HJnEq0d2-ep59A

###

GET http://localhost:8000/api/surveys
Authorization: Bearer {{token}}
###

GET http://localhost:8000/api/surveys/627d99fdf886fd167febcdd1
Authorization: Bearer {{token}}

###

POST http://localhost:8000/api/surveys
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Survey 7",
    "description": "This is a survey"
}

###

PUT http://localhost:8000/api/surveys/627db5d0898bf6302b2c201e
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Survey 12",
    "description": "This is a survey"
}

### 

DELETE http://localhost:8000/api/surveys/627d9a3af886fd167febcdd2
Authorization: Bearer {{token}}
